name: Julia Project
description: Instantiates a Julia project for use in your pipeline.
author: https://github.com/maleadt
requirements: [julia]
configuration:
  properties:
    coverage:
      type: boolean
    julia_args:
      type: string
    test_args:
      type: string
  additionalProperties: false
