name: Julia Test
description: Instantiates and tests a Julia project.
author: https://github.com/maleadt
requirements: [julia]
configuration:
  properties:
    coverage:
      type: boolean
    julia_args:
      type: string
    test_args:
      type: string
  additionalProperties: false
