#!/usr/bin/env bash
source $(dirname ${BASH_SOURCE})/common

# If there is a `commands` block specified in the YAML, run that as well
if [[ -n "${BUILDKITE_COMMAND}" ]]; then
    echo "+++ Running yaml-provided user commands"
    eval "${BUILDKITE_COMMAND}"
fi

# Use default julia test running harness
if [[ "${run_tests}" == "true" ]]; then
    echo "+++ :julia: Running tests"
    if [[ -z "${package}" ]]; then
        PKG=""
    else
        PKG="\"${package}\""
    fi
    julia ${bugreport_args} --color=yes --project=${project} -e "
        using Pkg

        # We never update the registry when running tests, we assume if you wanted this done, you'd do it in the pre-command
        Pkg.UPDATED_REGISTRY_THIS_SESSION[] = true

        # In the event that you might need to fetch test-only dependencies that are private,
        # we set Pkg to use SSH for cloning non-PkgServer-served packages here as well
        ${USE_SSH_BLOCK}

        Pkg.test(${PKG}; coverage=$coverage,
                    julia_args=\`$julia_args\`,
                    test_args=\`$test_args\`,
                    ${ALLOW_RERESOLVE_LINE})
    "
fi

# Restore the original Manifest
if [ -n "$custom_manifest" ]; then
    rm Manifest.toml
    mv Manifest.toml.bk_bak Manifest.toml
fi
