#!/usr/bin/env bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "${SCRIPT_DIR}/common"

# If we either always upload a trace (or only upload on error), pack it and append it to our artifact paths
if [[ "${upload_rr_trace}" == "always" ]] || ( [[ "${upload_rr_trace}" == "error" ]] && [[ "${BUILDKITE_COMMAND_EXIT_STATUS}" != "0" ]] ); then
    # Pack the trace directory into a .tar.zst
    julia "${SCRIPT_DIR}/pack_rr_trace.jl"
fi

# Clean up our `rr` directory no matter what
rm -rf "${_RR_TRACE_DIR}"
