#!/usr/bin/env bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "${SCRIPT_DIR}/common"

echo "--- :julia: Instantiating project"

if [ -n "$custom_manifest" ]; then
    mv Manifest.toml Manifest.toml.bk_bak
    cp "$custom_manifest" Manifest.toml
fi

JULIA_PKG_PRECOMPILE_AUTO=0 \
julia --project=${project} -e "
    using Pkg
    ${REGISTRY_SKIP_BLOCK}
    ${USE_SSH_BLOCK}
    ${ADD_REGISTRIES_BLOCK}

    Pkg.instantiate()
    Pkg.build()
    Pkg.status()
"

# Report this status so that `pre-exit` can count an instantiate failure as an overall failure too
export BUILDKITE_PLUGIN_JULIA_TEST_INSTANTIATE_STATUS="$?"
