#!/usr/bin/env bash
source $(dirname ${BASH_SOURCE})/common

echo "--- :julia: Instantiating project"

if [ -n "$custom_manifest" ]; then
    mv Manifest.toml Manifest.toml.bk_bak
    cp "$custom_manifest" Manifest.toml
fi

# when packages ship a manifest, we may need to resolve it before we can instantiate.
# we need to do this _outside_ of that environment, because Pkg may not be usable within.
if [ -f "Manifest.toml" ]; then
    echo "Resolving manifest..."
    julia -e "
        using Pkg
        Pkg.activate(\".\")
        Pkg.resolve()
    "
fi

JULIA_PKG_PRECOMPILE_AUTO=0 \
julia --project=${project} -e "
    using Pkg
    ${REGISTRY_SKIP_BLOCK}
    ${USE_SSH_BLOCK}
    ${ADD_REGISTRIES_BLOCK}

    Pkg.instantiate()
    Pkg.build()
    Pkg.status()
"
